sensor_name: "front_center"
sensor_model: "VL53L0X"
frequency: 20
mode: "BETTER"
display_fragment_frequency: 4
connectors:
  # DB21M and DB21J (based on Jetson Nano A02)
  -   bus: 13
      address: 0x29
  # DB21J (based on Jetson Nano B01)
  -   bus: 15
      address: 0x29
  # fallback: connected directly to the HUT (any model)
  -   bus: 1
      address: 0x29
