sensor_name: "left"
sensor_model: "VL53L1X"
frequency: 30
mode: "LONG_RANGE"
display_fragment_frequency: 0
connectors:
  # Raspberry Pi 4
  # left ToF -> mux channel 3 (i2c-26)
  -   bus: 26
      address: 0x29

  # Raspberry Pi 5
  -   bus: 11
      address: 0x29