sensor_name: "bottom"
sensor_model: "VL53L1X"
frequency: 30
mode: "LONG_RANGE"
display_fragment_frequency: 0
connectors:
  # DD24 - One ToF sensor connected directly to the HUT
  # Raspberry Pi 4
  -   bus: 22
      address: 0x29

  # Raspberry Pi 5
  -   bus: 11
      address: 0x29