sensor_name: "right"
sensor_model: "VL53L1X"
frequency: 5  # Hz
mode: "LONG_RANGE"
display_fragment_frequency: 0
connectors:
  # Raspberry Pi 4
  # right ToF -> port CHL2
  -   bus: 25
      address: 0x29

  # Raspberry Pi 5
  # TODO: verify bus on Pi 5
  -   bus: 11
      address: 0x29